### ISSUE TITLE
not Parsing Epub

### ISSUE THREAD

**Issue by blennerSilva** [readium/readium-2#60]
He guys this is my problem:

im getting this log error:

##Log

E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.folioreader.android.sample, PID: 17486
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.folioreader.android.sample/com.folioreader.ui.folio.activity.FolioActivity}: java.lang.NullPointerException: Attempt to read from field 'java.util.List org.readium.r2_streamer.model.publication.EpubPublication.links' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.List org.readium.r2_streamer.model.publication.EpubPublication.links' on a null object reference
at org.readium.r2_streamer.server.EpubServer.addLinks(EpubServer.java:68)
at org.readium.r2_streamer.server.EpubServer.addEpub(EpubServer.java:42)
at com.folioreader.ui.folio.activity.FolioActivity.addEpub(FolioActivity.java:223)
at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:211)
at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:623)
at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:161)
at android.app.Activity.performCreate(Activity.java:6245)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

here are the two examples of books that im using : this first one works

https://user-images.githubusercontent.com/10924301/34876138-6f552be8-f787-11e7-9ef0-8ea35511c2b4.png

this one crashes everytime:

https://user-images.githubusercontent.com/10924301/34876141-7442293a-f787-11e7-928a-e8331085b1f7.png

as you can se the files are different and i cant launch with this bug can you help me?

Updating my issue im getting:
android - org.xml.sax.SAXParseException: Unexpected token (position:TEXT @1:2 in java.io.StringReader@4156ccc8) -

**Comment by HadrienGardeur** [comment]
This should be posted on the appropriate repo instead and I see a duplicate on the Java repo (btw you should try the Kotlin streamer instead).
